# Generated by Django 5.2.13 on 2026-05-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employeeavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('start_time', models.TimeField(verbose_name='Начало смены')),
                ('end_time', models.TimeField(verbose_name='Окончание смены')),
                ('zone', models.CharField(choices=[('main', 'Основной зал'), ('terrace', 'Терраса'), ('vip', 'VIP-зона'), ('bar', 'Бар'), ('kitchen', 'Кухня'), ('other', 'Другая зона')], default='main', max_length=30, verbose_name='Зона работы')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('is_manual', models.BooleanField(default=True, verbose_name='Назначено вручную')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('external_shift_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID смены во внешнем модуле')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Подтверждённая смена',
                'verbose_name_plural': 'Подтверждённые смены',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
