# Generated by Django 5.2.13 on 2026-05-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_confirmedshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedshift',
            name='external_shift_id',
        ),
        migrations.AddField(
            model_name='confirmedshift',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shifts', to='staff.employeeavailability', verbose_name='Интервал доступности'),
        ),
    ]
