# Generated by Django 5.2.13 on 2026-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_tablefeature_restauranttable_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_booking_enabled', models.BooleanField(default=True)),
                ('online_booking_percent', models.PositiveIntegerField(default=100)),
                ('reserved_for_walkin_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
