# Generated by Django 5.2.13 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменено')], default='active', max_length=20),
        ),
    ]
