# Generated by Django 5.2.13 on 2026-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_booking_code_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_schemes/', verbose_name='Изображение схемы зала')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Номер бронирования'),
        ),
    ]
