# Generated by Django 5.2.13 on 2026-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_hallscheme_alter_reservation_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='shape',
            field=models.CharField(choices=[('round', 'Круглый'), ('rect', 'Прямоугольный')], default='rect', max_length=20),
        ),
    ]
