# Generated by Django 5.2.13 on 2026-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_restauranttable_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='booking_end_time',
            field=models.TimeField(default='22:00', verbose_name='Конец интервала бронирования'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='booking_start_time',
            field=models.TimeField(default='10:00', verbose_name='Начало интервала бронирования'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='max_days_ahead',
            field=models.PositiveIntegerField(default=30, verbose_name='Максимальный период предварительного бронирования в днях'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='min_time_before_booking_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Минимальное время до начала бронирования в минутах'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='reservation_duration_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='Длительность бронирования в минутах'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='online_booking_enabled',
            field=models.BooleanField(default=True, verbose_name='Онлайн-бронирование включено'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='online_booking_percent',
            field=models.PositiveIntegerField(default=100, verbose_name='Доля столиков для онлайн-бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='reserved_for_walkin_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество столиков для живой посадки'),
        ),
    ]
